name: 更新金价

on:
  schedule:
    - cron: '0 1 * * *'  # 每天UTC时间1点（即北京时间9点）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # 如果您的仓库是公开的，使用上面的token即可。如果是私有的，可能需要个人访问令牌（PAT）

    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 安装依赖
      run: npm install axios

    - name: 获取金价并生成文件
      run: node update-price.js

    - name: 提交更改
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add price.txt
        git commit -m "自动更新金价数据" || exit 0
        git push
